export const actions = {
  SET_EMPLOYEES: "SET_EMPLOYEES",
  UPDATE_EMPLOYEE_ID: "UPDATE_EMPLOYEE_ID",
  SET_EMPLOYEE: "SET_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",

  SET_SKILLS: "SET_SKILLS",
  SET_DEPARTMENTS: "SET_DEPARTMENTS",

  SET_PREV_EMPLOYEE: "SET_PREV_EMPLOYEE",
  DELETE_PREV_EMPLOYEE: "DELETE_PREV_EMPLOYEE",
};
